# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0003_auto_20161111_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='course',
            name='mark_num',
            field=models.IntegerField(default=0),
        ),
    ]
