# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='begin_time',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
