# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0006_auto_20161114_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
