# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0007_lesson_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='classification',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='mooc.Classification'),
            preserve_default=False,
        ),
    ]
