# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0010_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='pinyin',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
